/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as TopicsTopicIdThreadsRouteImport } from './routes/topics.$topicId.threads'
import { Route as TopicsTopicIdThreadsThreadUuidRouteImport } from './routes/topics.$topicId.threads.$threadUuid'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => TopicsRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdThreadsRoute = TopicsTopicIdThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => TopicsTopicIdRoute,
} as any)
const TopicsTopicIdThreadsThreadUuidRoute =
  TopicsTopicIdThreadsThreadUuidRouteImport.update({
    id: '/$threadUuid',
    path: '/$threadUuid',
    getParentRoute: () => TopicsTopicIdThreadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/welcome': typeof WelcomeRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/topics/$topicId/threads': typeof TopicsTopicIdThreadsRouteWithChildren
  '/topics/$topicId/threads/$threadUuid': typeof TopicsTopicIdThreadsThreadUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/welcome': typeof WelcomeRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/topics/$topicId/threads': typeof TopicsTopicIdThreadsRouteWithChildren
  '/topics/$topicId/threads/$threadUuid': typeof TopicsTopicIdThreadsThreadUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/trending': typeof TrendingRoute
  '/welcome': typeof WelcomeRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRouteWithChildren
  '/topics/$topicId/threads': typeof TopicsTopicIdThreadsRouteWithChildren
  '/topics/$topicId/threads/$threadUuid': typeof TopicsTopicIdThreadsThreadUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/following'
    | '/login'
    | '/profile-setup'
    | '/search'
    | '/settings'
    | '/topics'
    | '/trending'
    | '/welcome'
    | '/profile/$userId'
    | '/topics/$topicId'
    | '/topics/$topicId/threads'
    | '/topics/$topicId/threads/$threadUuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/following'
    | '/login'
    | '/profile-setup'
    | '/search'
    | '/settings'
    | '/topics'
    | '/trending'
    | '/welcome'
    | '/profile/$userId'
    | '/topics/$topicId'
    | '/topics/$topicId/threads'
    | '/topics/$topicId/threads/$threadUuid'
  id:
    | '__root__'
    | '/'
    | '/following'
    | '/login'
    | '/profile-setup'
    | '/search'
    | '/settings'
    | '/topics'
    | '/trending'
    | '/welcome'
    | '/profile/$userId'
    | '/topics/$topicId'
    | '/topics/$topicId/threads'
    | '/topics/$topicId/threads/$threadUuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  TrendingRoute: typeof TrendingRoute
  WelcomeRoute: typeof WelcomeRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/threads': {
      id: '/topics/$topicId/threads'
      path: '/threads'
      fullPath: '/topics/$topicId/threads'
      preLoaderRoute: typeof TopicsTopicIdThreadsRouteImport
      parentRoute: typeof TopicsTopicIdRoute
    }
    '/topics/$topicId/threads/$threadUuid': {
      id: '/topics/$topicId/threads/$threadUuid'
      path: '/$threadUuid'
      fullPath: '/topics/$topicId/threads/$threadUuid'
      preLoaderRoute: typeof TopicsTopicIdThreadsThreadUuidRouteImport
      parentRoute: typeof TopicsTopicIdThreadsRoute
    }
  }
}

interface TopicsTopicIdThreadsRouteChildren {
  TopicsTopicIdThreadsThreadUuidRoute: typeof TopicsTopicIdThreadsThreadUuidRoute
}

const TopicsTopicIdThreadsRouteChildren: TopicsTopicIdThreadsRouteChildren = {
  TopicsTopicIdThreadsThreadUuidRoute: TopicsTopicIdThreadsThreadUuidRoute,
}

const TopicsTopicIdThreadsRouteWithChildren =
  TopicsTopicIdThreadsRoute._addFileChildren(TopicsTopicIdThreadsRouteChildren)

interface TopicsTopicIdRouteChildren {
  TopicsTopicIdThreadsRoute: typeof TopicsTopicIdThreadsRouteWithChildren
}

const TopicsTopicIdRouteChildren: TopicsTopicIdRouteChildren = {
  TopicsTopicIdThreadsRoute: TopicsTopicIdThreadsRouteWithChildren,
}

const TopicsTopicIdRouteWithChildren = TopicsTopicIdRoute._addFileChildren(
  TopicsTopicIdRouteChildren,
)

interface TopicsRouteChildren {
  TopicsTopicIdRoute: typeof TopicsTopicIdRouteWithChildren
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsTopicIdRoute: TopicsTopicIdRouteWithChildren,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TopicsRoute: TopicsRouteWithChildren,
  TrendingRoute: TrendingRoute,
  WelcomeRoute: WelcomeRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
