import { expect, test } from '@playwright/test';
import { DEVELOPER_MODE_STORAGE_KEY } from '../../src/lib/developerMode';

test('camera capture, real wheel and keyboard UI round trips preserve the Column and draft', async ({ page }) => {
  await page.addInitScript(key => localStorage.setItem(key, 'true'), DEVELOPER_MODE_STORAGE_KEY);
  await page.setViewportSize({ width: 1280, height: 870 });
  await page.goto('/#/timeline?topic=kukuri%3Atopic%3Ageneral');
  await page.getByTestId('control-center-trigger').click();
  await page.getByRole('button', { name: 'Add Metaverse Column' }).click();
  const column = page.getByRole('region', { name: /^Metaverse Column/ });
  const create = column.getByRole('button', { name: 'Create metaverse room' }).first();
  if (await create.getAttribute('aria-expanded') === 'false') await create.click();
  await column.getByPlaceholder('Atrium').fill('Camera regression');
  await column.getByRole('button', { name: 'Create metaverse room' }).last().click();
  await column.getByRole('button', { name: 'Start hosting and enter' }).click();
  const stage = column.locator('[data-column-gesture-owner="metaverse"]');
  await expect(stage).toBeVisible();
  await expect(stage).toHaveAttribute('data-input-mode', 'idle');
  await stage.locator('canvas').click({ position: { x: 550, y: 260 } });
  await expect(stage).toHaveAttribute('data-input-mode', 'locked');
  await expect.poll(() => page.evaluate(() => document.pointerLockElement?.tagName)).toBe('CANVAS');
  const scrolls = () => column.evaluate(el => [el.scrollTop, el.querySelector('.shell-column-body')?.scrollTop, document.scrollingElement?.scrollTop]);
  const before = await scrolls();
  const box = (await stage.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2 + 100, box.y + box.height / 2);
  await page.mouse.wheel(0, 180);
  await page.waitForTimeout(100);
  expect(await scrolls()).toEqual(before);
  await page.keyboard.press('Tab');
  await expect(stage).toHaveAttribute('data-input-mode', 'idle');
  await expect(stage.getByRole('button', { name: 'Debug details' })).toBeFocused();
  expect(await page.evaluate(() => document.pointerLockElement)).toBeNull();
  await page.keyboard.press('Escape');
  await expect(stage).toBeFocused();
  await page.keyboard.press('Enter');
  const chat = stage.getByLabel('Room chat message');
  await expect(chat).toBeFocused();
  await chat.fill('camera draft');
  await page.keyboard.press('Escape');
  await expect(chat).toHaveCount(0);
  await page.keyboard.press('Enter');
  await expect(chat).toHaveValue('camera draft');
  await page.keyboard.press('Escape');
  await stage.getByText('Adjust view', { exact: true }).click();
  await stage.getByRole('button', { name: 'Reset camera' }).click();
  await stage.getByRole('button', { name: 'Resume avatar controls' }).click();
  await expect(stage).toHaveAttribute('data-input-mode', 'locked');
  await page.keyboard.press('Escape');
  await expect(stage).toHaveAttribute('data-input-mode', 'idle');
  await expect(column).toHaveAttribute('aria-current', 'true');
});
