//! operator config から terraform の env 設定（`terraform.tfvars`）を決定論的に生成する（#380）。
//!
//! `cn-operator generate-tfvars` は operator-config.yaml を単一の入力元として、
//! `infra/terraform/envs/low-cost` 用の `terraform.tfvars` を出力する。これにより運営者は
//! 同じ config から docs / manifest と terraform の env 設定の両方を得られる。
//!
//! 重要な不変条件:
//! - secret は **値ではなく Secret Manager の secret ID** のみを出力する（payload は出さない）。
//! - blob cache の on/off は `features.blob_cache` を真実源にして導出する（deploy 側で重複させない）。
//! - 出力は wall-clock 非依存で、同じ config からは同じ tfvars が得られる（決定論）。

use std::fmt::Write as _;

use anyhow::{Result, bail};

use crate::config::{DeployConfig, DeployProfile, ResolvedConfig};

/// operator-config から `terraform.tfvars`（HCL 文字列）を生成する。
///
/// `deploy` セクションが未指定の場合や、tfvars 生成未対応の profile の場合は error にする。
pub fn generate_tfvars(config: &ResolvedConfig) -> Result<String> {
    let Some(deploy) = config.deploy() else {
        bail!(
            "deploy セクションが指定されていません。\n\
             terraform.tfvars を生成するには operator-config.yaml に deploy: を追加してください。"
        );
    };

    if deploy.profile != DeployProfile::LowCost {
        bail!(
            "deploy.profile `{}` の tfvars 生成は未対応です（拡張点）。\n\
             現在 generate-tfvars が対応するのは low-cost のみです。",
            deploy.profile.key()
        );
    }

    Ok(render_low_cost_tfvars(config, deploy))
}

/// HCL の文字列値をダブルクォートで安全に出力する。
fn hcl_string(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// low-cost env 用の tfvars を決定論的に組み立てる。
fn render_low_cost_tfvars(config: &ResolvedConfig, deploy: &DeployConfig) -> String {
    let project_id = deploy.project_id.trim();
    let region = deploy.region.trim();
    let zone = deploy.zone.trim();
    let api_domain = config.api_domain().trim();
    let relay_domain = deploy.relay_domain.as_deref().map(str::trim).unwrap_or("");
    let acme_email = deploy.acme_email.trim();
    let blob_cache_enabled = config.blob_cache_enabled();
    let dns_zone_name = deploy.dns_zone_name.as_deref().map(str::trim).unwrap_or("");
    let cn_user_api_image = deploy.cn_user_api_image.trim();
    let cn_iroh_relay_image = deploy.cn_iroh_relay_image.trim();
    let cn_cli_image = deploy.cn_cli_image.trim();
    let jwt_secret_id = deploy.jwt_secret_id.trim();
    let postgres_password_secret_id = deploy.postgres_password_secret_id.trim();
    let safety_signing_key_secret_id = config
        .raw
        .safety
        .as_ref()
        .and_then(|safety| safety.events.signing_key_secret_id.as_deref())
        .map(str::trim)
        .unwrap_or("");
    let machine_type = deploy.machine_type.trim();
    let blob_cache_path = deploy.blob_cache_path.trim();

    let mut out = String::new();
    let _ = writeln!(
        out,
        "# Generated by `cn-operator generate-tfvars` from operator-config.yaml. Do not edit by hand."
    );
    let _ = writeln!(
        out,
        "# Re-run generate-tfvars after changing operator-config.yaml. Secret VALUES are never"
    );
    let _ = writeln!(
        out,
        "# written here; only Secret Manager secret IDs. terraform.tfvars is gitignored."
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "project_id = {}", hcl_string(project_id));
    let _ = writeln!(out, "region     = {}", hcl_string(region));
    let _ = writeln!(out, "zone       = {}", hcl_string(zone));
    let _ = writeln!(out);

    let _ = writeln!(out, "api_domain   = {}", hcl_string(api_domain));
    let _ = writeln!(out, "relay_domain = {}", hcl_string(relay_domain));
    let _ = writeln!(out, "acme_email   = {}", hcl_string(acme_email));
    let _ = writeln!(out);

    let _ = writeln!(out, "manage_cloud_dns = {}", deploy.manage_cloud_dns);
    let _ = writeln!(out, "dns_zone_name    = {}", hcl_string(dns_zone_name));
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "cn_user_api_image   = {}",
        hcl_string(cn_user_api_image)
    );
    let _ = writeln!(
        out,
        "cn_iroh_relay_image = {}",
        hcl_string(cn_iroh_relay_image)
    );
    let _ = writeln!(out, "cn_cli_image        = {}", hcl_string(cn_cli_image));
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "jwt_secret_id               = {}",
        hcl_string(jwt_secret_id)
    );
    let _ = writeln!(
        out,
        "postgres_password_secret_id = {}",
        hcl_string(postgres_password_secret_id)
    );
    let _ = writeln!(
        out,
        "safety_signing_key_secret_id = {}",
        hcl_string(safety_signing_key_secret_id)
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "machine_type          = {}", hcl_string(machine_type));
    let _ = writeln!(out, "disk_size_gb          = {}", deploy.disk_size_gb);
    let _ = writeln!(
        out,
        "postgres_data_disk_gb = {}",
        deploy.postgres_data_disk_gb
    );
    let _ = writeln!(out);

    // blob cache の on/off は features.blob_cache が真実源。sizing は deploy から取る。
    let _ = writeln!(out, "blob_cache_enabled   = {blob_cache_enabled}");
    let _ = writeln!(out, "blob_cache_size_gb   = {}", deploy.blob_cache_size_gb);
    let _ = writeln!(
        out,
        "blob_cache_ttl_hours = {}",
        deploy.blob_cache_ttl_hours
    );
    let _ = writeln!(
        out,
        "blob_cache_path      = {}",
        hcl_string(blob_cache_path)
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "rate_limit_enabled    = {}", deploy.rate_limit_enabled);
    let _ = writeln!(
        out,
        "rate_limit_per_second = {}",
        deploy.rate_limit_per_second
    );
    let _ = writeln!(out, "rate_limit_burst      = {}", deploy.rate_limit_burst);
    let _ = writeln!(out);

    let _ = writeln!(out, "backup_enabled        = {}", deploy.backup_enabled);
    let _ = writeln!(
        out,
        "backup_retention_days = {}",
        deploy.backup_retention_days
    );

    // operator-config.yaml 自体を VM に配置して manifest endpoint / report_endpoint gating を
    // 有効化する。中身はこの tfvars には埋めず、Terraform 側の .tf で file() する。
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "# operator-config.yaml を VM へ配置して public manifest endpoint /"
    );
    let _ = writeln!(
        out,
        "# report_endpoint gating を有効化する。env dir からの相対 path を指定する:"
    );
    let _ = writeln!(out, "# operator_config_path = \"operator-config.yaml\"");

    out
}
