//! IPC 型の TypeScript 生成(WP-H7 PR3。`ts` feature 時のみ)。
//!
//! 生成器は client 依存グラフの頂点である desktop-runtime に置く。ここからは
//! app-api(views)/ core / store / transport / cn-protocol / 自 crate の
//! community-node 型まで全 IPC 型に到達できる。
//!
//! `cargo test -p kukuri-desktop-runtime --features ts export_ipc_types` で
//! `apps/desktop/src/lib/api/types.generated.ts` を再生成する。xtask `ipc-types`
//! が `TS_RS_LARGE_INT=number` を設定して実行し、CI は再生成後の
//! `git diff --exit-code` で Rust と TS の乖離を検出する。
//!
//! front 専用型(入力 DTO / エラー型 / DesktopApi interface)は手書きの
//! types.ts 側に残す。
#![cfg(feature = "ts")]

use ts_rs::TS;

const HEADER: &str = "// @generated by `cargo xtask ipc-types` from Rust IPC types. DO NOT EDIT.\n\
// 手で編集せず、Rust 側(crates/app-api/src/views.rs ほか)を変更して再生成すること。\n\n";

fn emit<T: TS>(cfg: &ts_rs::Config, out: &mut String) {
    out.push_str("export ");
    out.push_str(<T as TS>::decl(cfg).trim_end_matches(';'));
    out.push_str(";\n\n");
}

#[test]
fn export_ipc_types() {
    use crate::{
        CommunityNodeAuthState, CommunityNodeAuthorityScope, CommunityNodeCapabilityScope,
        CommunityNodeConfig, CommunityNodeManifest, CommunityNodeManifestFetch,
        CommunityNodeManifestFetchStatus, CommunityNodeNodeConfig, CommunityNodeNodeStatus,
        CommunityNodeP2pBoundary, CommunityNodeSessionPhase, DiscoveryConfig, RuntimeEvent,
        SubmitCommunityNodeReportRequest, SubmitCommunityNodeReportResult,
        SubmitCommunityNodeReportStatus,
    };
    use kukuri_app_api::*;
    use kukuri_cn_protocol::{
        CommunityNodeConsentItem, CommunityNodeConsentStatus, CommunityNodeResolvedUrls,
        CommunityNodeSeedPeer,
    };
    use kukuri_core::{
        ChannelAudienceKind, ChannelId, ChannelRef, ChannelSharingState, FriendOnlyGrantPreview,
        FriendPlusSharePreview, GameRoomKind, GameRoomStatus, LiveSessionStatus,
        MetaverseAssetKind, MetaverseAssetRef, MetaverseAvatarTransformV1, MetaversePrimitive,
        MetaverseRoomChatMessageV1, MetaverseRoomEventEnvelopeContentV1, MetaverseRoomEventV1,
        MetaverseRoomPresenceV1, MetaverseRoomSceneV1, MetaverseRoomSpawnV1, MetaverseRoomStateV1,
        PrivateChannelInvitePreview, Profile, Pubkey, SharedRoomObjectV1, TimelineScope, TopicId,
    };
    use kukuri_store::TimelineCursor;
    use kukuri_transport::{ConnectMode, ConnectionPath, DiscoveryMode, SeedPeer};

    let cfg = ts_rs::Config::from_env();
    let mut out = String::from(HEADER);

    macro_rules! emit_all {
        ($($t:ty),+ $(,)?) => { $( emit::<$t>(&cfg, &mut out); )+ };
    }

    emit_all!(
        TimelineCursor,
        ChannelAudienceKind,
        ChannelSharingState,
        DiscoveryMode,
        ConnectMode,
        ConnectionPath,
        SocialConnectionKind,
        BlobViewStatus,
        DeliveryState,
        NotificationKind,
        ChannelAccessTokenKind,
        ProfileAssetView,
        AttachmentView,
        BlobMediaPayload,
        ReplyPreviewAuthorView,
        ReplyPreviewView,
        ReactionKeyView,
        ReactionSummaryView,
        ReactionStateView,
        RecentReactionView,
        CustomReactionAssetView,
        RepostSourceView,
        PostView,
        BookmarkedPostView,
        AuthorSocialView,
        DirectMessageStatusView,
        DirectMessageTopicStatusView,
        DirectMessageMessageView,
        DirectMessageConversationView,
        NotificationView,
        NotificationStatusView,
        TimelineView,
        DirectMessageTimelineView,
        JoinedPrivateChannelView,
        PrivateChannelEpochCapability,
        PrivateChannelCapability,
        ChannelAccessTokenExport,
        ChannelAccessTokenPreview,
        TopicSyncStatus,
        DiscoveryStatus,
        SyncStatus,
        // metaverse / game / live
        LiveSessionStatus,
        LiveSessionView,
        GameRoomStatus,
        GameRoomKind,
        GameScoreView,
        MetaverseAssetKind,
        MetaverseAssetRef,
        MetaversePrimitive,
        MetaverseRoomPresenceV1,
        MetaverseAvatarTransformV1,
        MetaverseRoomChatMessageV1,
        SharedRoomObjectV1,
        MetaverseRoomEventV1,
        MetaverseRoomEventEnvelopeContentV1,
        MetaverseRoomSceneV1,
        MetaverseRoomSpawnV1,
        MetaverseRoomStateV1,
        GameRoomView,
        MetaverseRoomEventView,
        // core / transport の残り + newtype(string)
        Pubkey,
        TopicId,
        ChannelId,
        ChannelRef,
        TimelineScope,
        SeedPeer,
        Profile,
        PrivateChannelInvitePreview,
        FriendOnlyGrantPreview,
        FriendPlusSharePreview,
        // community-node(desktop-runtime / cn-protocol)
        DiscoveryConfig,
        CommunityNodeSeedPeer,
        CommunityNodeResolvedUrls,
        CommunityNodeNodeConfig,
        CommunityNodeConfig,
        CommunityNodeAuthState,
        CommunityNodeConsentItem,
        CommunityNodeConsentStatus,
        CommunityNodeSessionPhase,
        CommunityNodeNodeStatus,
        CommunityNodeCapabilityScope,
        CommunityNodeAuthorityScope,
        CommunityNodeP2pBoundary,
        CommunityNodeManifest,
        CommunityNodeManifestFetchStatus,
        CommunityNodeManifestFetch,
        SubmitCommunityNodeReportRequest,
        SubmitCommunityNodeReportStatus,
        SubmitCommunityNodeReportResult,
        RuntimeEvent,
    );

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../apps/desktop/src/lib/api/types.generated.ts"
    );
    std::fs::write(path, out).unwrap();
}
