//! IPC 型の TypeScript 生成(WP-H7 PR3。`ts` feature 時のみ)。
//!
//! `cargo test -p kukuri-app-api --features ts export_ipc_types` で
//! `apps/desktop/src/lib/api/types.generated.ts` を再生成する。
//! xtask `ipc-types` が `TS_RS_LARGE_INT=number` を設定してこれを実行し、
//! 続けて prettier を掛ける。CI は再生成後に `git diff --exit-code` で
//! Rust と TS の乖離(手動同期漏れ)を検出する。
//!
//! Stage 1 の生成対象は app-api の view サブグラフ(metaverse/game/live は
//! 後続ステージ)。front 専用型・入力型・DesktopApi interface は
//! 手書きの types.ts 側に残す。
#![cfg(feature = "ts")]

use ts_rs::TS;

const HEADER: &str = "// @generated by `cargo xtask ipc-types` from Rust IPC types. DO NOT EDIT.\n\
// 手で編集せず、Rust 側(crates/app-api/src/views.rs ほか)を変更して再生成すること。\n\n";

fn emit<T: TS>(cfg: &ts_rs::Config, out: &mut String) {
    out.push_str("export ");
    out.push_str(<T as TS>::decl(cfg).trim_end_matches(';'));
    out.push_str(";\n\n");
}

#[test]
fn export_ipc_types() {
    use crate::views::*;
    use kukuri_core::{
        ChannelAudienceKind, ChannelId, ChannelRef, ChannelSharingState, FriendOnlyGrantPreview,
        FriendPlusSharePreview, GameRoomKind, GameRoomStatus, LiveSessionStatus,
        MetaverseAssetKind, MetaverseAssetRef, MetaverseAvatarTransformV1, MetaversePrimitive,
        MetaverseRoomChatMessageV1, MetaverseRoomEventEnvelopeContentV1, MetaverseRoomEventV1,
        MetaverseRoomPresenceV1, MetaverseRoomSceneV1, MetaverseRoomSpawnV1, MetaverseRoomStateV1,
        PrivateChannelInvitePreview, Profile, Pubkey, SharedRoomObjectV1, TimelineScope, TopicId,
    };
    use kukuri_store::{NotificationKind, TimelineCursor};
    use kukuri_transport::{ConnectMode, ConnectionPath, DiscoveryMode, SeedPeer};

    let cfg = ts_rs::Config::from_env();
    let mut out = String::from(HEADER);

    macro_rules! emit_all {
        ($($t:ty),+ $(,)?) => { $( emit::<$t>(&cfg, &mut out); )+ };
    }

    emit_all!(
        TimelineCursor,
        ChannelAudienceKind,
        ChannelSharingState,
        DiscoveryMode,
        ConnectMode,
        ConnectionPath,
        SocialConnectionKind,
        BlobViewStatus,
        DeliveryState,
        NotificationKind,
        ChannelAccessTokenKind,
        ProfileAssetView,
        AttachmentView,
        BlobMediaPayload,
        ReplyPreviewAuthorView,
        ReplyPreviewView,
        ReactionKeyView,
        ReactionSummaryView,
        ReactionStateView,
        RecentReactionView,
        CustomReactionAssetView,
        RepostSourceView,
        PostView,
        BookmarkedPostView,
        AuthorSocialView,
        DirectMessageStatusView,
        DirectMessageTopicStatusView,
        DirectMessageMessageView,
        DirectMessageConversationView,
        NotificationView,
        NotificationStatusView,
        TimelineView,
        DirectMessageTimelineView,
        JoinedPrivateChannelView,
        PrivateChannelEpochCapability,
        PrivateChannelCapability,
        ChannelAccessTokenExport,
        ChannelAccessTokenPreview,
        TopicSyncStatus,
        DiscoveryStatus,
        SyncStatus,
        // Stage 2: metaverse / game / live
        LiveSessionStatus,
        LiveSessionView,
        GameRoomStatus,
        GameRoomKind,
        GameScoreView,
        MetaverseAssetKind,
        MetaverseAssetRef,
        MetaversePrimitive,
        MetaverseRoomPresenceV1,
        MetaverseAvatarTransformV1,
        MetaverseRoomChatMessageV1,
        SharedRoomObjectV1,
        MetaverseRoomEventV1,
        MetaverseRoomEventEnvelopeContentV1,
        MetaverseRoomSceneV1,
        MetaverseRoomSpawnV1,
        MetaverseRoomStateV1,
        GameRoomView,
        MetaverseRoomEventView,
        // Stage 3a: core / transport の残り型 + newtype(string)
        Pubkey,
        TopicId,
        ChannelId,
        ChannelRef,
        TimelineScope,
        SeedPeer,
        Profile,
        PrivateChannelInvitePreview,
        FriendOnlyGrantPreview,
        FriendPlusSharePreview,
    );

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../apps/desktop/src/lib/api/types.generated.ts"
    );
    std::fs::write(path, out).unwrap();
}
