//! IPC 型の TypeScript 生成(WP-H7 PR3。`ts` feature 時のみ)。
//!
//! `cargo test -p kukuri-app-api --features ts export_ipc_types` で
//! `apps/desktop/src/lib/api/types.generated.ts` を再生成する。
//! xtask `ipc-types` が `TS_RS_LARGE_INT=number` を設定してこれを実行し、
//! 続けて prettier を掛ける。CI は再生成後に `git diff --exit-code` で
//! Rust と TS の乖離(手動同期漏れ)を検出する。
//!
//! Stage 1 の生成対象は app-api の view サブグラフ(metaverse/game/live は
//! 後続ステージ)。front 専用型・入力型・DesktopApi interface は
//! 手書きの types.ts 側に残す。
#![cfg(feature = "ts")]

use ts_rs::TS;

const HEADER: &str = "// @generated by `cargo xtask ipc-types` from Rust IPC types. DO NOT EDIT.\n\
// 手で編集せず、Rust 側(crates/app-api/src/views.rs ほか)を変更して再生成すること。\n\n";

fn emit<T: TS>(cfg: &ts_rs::Config, out: &mut String) {
    out.push_str("export ");
    out.push_str(<T as TS>::decl(cfg).trim_end_matches(';'));
    out.push_str(";\n\n");
}

#[test]
fn export_ipc_types() {
    use crate::views::*;
    use kukuri_core::{ChannelAudienceKind, ChannelSharingState};
    use kukuri_store::{NotificationKind, TimelineCursor};
    use kukuri_transport::{ConnectMode, ConnectionPath, DiscoveryMode};

    let cfg = ts_rs::Config::from_env();
    let mut out = String::from(HEADER);

    macro_rules! emit_all {
        ($($t:ty),+ $(,)?) => { $( emit::<$t>(&cfg, &mut out); )+ };
    }

    emit_all!(
        TimelineCursor,
        ChannelAudienceKind,
        ChannelSharingState,
        DiscoveryMode,
        ConnectMode,
        ConnectionPath,
        SocialConnectionKind,
        BlobViewStatus,
        DeliveryState,
        NotificationKind,
        ChannelAccessTokenKind,
        ProfileAssetView,
        AttachmentView,
        BlobMediaPayload,
        ReplyPreviewAuthorView,
        ReplyPreviewView,
        ReactionKeyView,
        ReactionSummaryView,
        ReactionStateView,
        RecentReactionView,
        CustomReactionAssetView,
        RepostSourceView,
        PostView,
        BookmarkedPostView,
        AuthorSocialView,
        DirectMessageStatusView,
        DirectMessageTopicStatusView,
        DirectMessageMessageView,
        DirectMessageConversationView,
        NotificationView,
        NotificationStatusView,
        TimelineView,
        DirectMessageTimelineView,
        JoinedPrivateChannelView,
        PrivateChannelEpochCapability,
        PrivateChannelCapability,
        ChannelAccessTokenExport,
        ChannelAccessTokenPreview,
        TopicSyncStatus,
        DiscoveryStatus,
        SyncStatus,
    );

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../apps/desktop/src/lib/api/types.generated.ts"
    );
    std::fs::write(path, out).unwrap();
}
