version: '3.8'

services:
  # Primary bootstrap node
  bootstrap-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kukuri-bootstrap-1
    environment:
      - LOG_LEVEL=info
      - BIND_ADDRESS=0.0.0.0:11223
    ports:
      - "11223:11223"
    networks:
      - kukuri-net
    volumes:
      - bootstrap1-data:/home/kukuri/data
    restart: unless-stopped
    command: ["bootstrap"]

  # Secondary bootstrap node
  bootstrap-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kukuri-bootstrap-2
    environment:
      - LOG_LEVEL=info
      - BIND_ADDRESS=0.0.0.0:11224
    ports:
      - "11224:11224"
    networks:
      - kukuri-net
    volumes:
      - bootstrap2-data:/home/kukuri/data
    restart: unless-stopped
    command: ["bootstrap", "--bind", "0.0.0.0:11224"]
    depends_on:
      - bootstrap-node-1

  # Relay node for topic distribution
  relay-node-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kukuri-relay-1
    environment:
      - LOG_LEVEL=info
      - BIND_ADDRESS=0.0.0.0:11225
    ports:
      - "11225:11225"
    networks:
      - kukuri-net
    volumes:
      - relay1-data:/home/kukuri/data
    restart: unless-stopped
    command: ["relay", "--bind", "0.0.0.0:11225", "--topics", "kukuri,test,development"]
    depends_on:
      - bootstrap-node-1
      - bootstrap-node-2

  # Optional: Additional relay node
  relay-node-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kukuri-relay-2
    environment:
      - LOG_LEVEL=info
      - BIND_ADDRESS=0.0.0.0:11226
      - JSON_LOGS=true
    ports:
      - "11226:11226"
    networks:
      - kukuri-net
    volumes:
      - relay2-data:/home/kukuri/data
    restart: unless-stopped
    command: ["relay", "--bind", "0.0.0.0:11226", "--topics", "kukuri,production"]
    depends_on:
      - bootstrap-node-1
      - bootstrap-node-2
    profiles:
      - full  # Only starts with --profile full

networks:
  kukuri-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  bootstrap1-data:
  bootstrap2-data:
  relay1-data:
  relay2-data: