// @generated by `cargo xtask ipc-types` from Rust IPC types. DO NOT EDIT.
// 手で編集せず、Rust 側(crates/app-api/src/views.rs ほか)を変更して再生成すること。

export type TimelineCursor = { created_at: number, object_id: string, };

export type ChannelAudienceKind = "invite_only" | "friend_only" | "friend_plus";

export type ChannelSharingState = "open" | "frozen";

export type DiscoveryMode = "static_peer" | "seeded_dht";

export type ConnectMode = "direct_only" | "direct_or_relay";

export type ConnectionPath = "direct_p2p" | "relay_supported_p2p" | "relay_fallback";

export type SocialConnectionKind = "following" | "followed" | "muted";

export type BlobViewStatus = "Missing" | "Available" | "Pinned";

export type DeliveryState = "Live" | "DurableRecovering" | "DurableReady" | "Offline";

export type NotificationKind = "mention" | "reply" | "repost" | "quote_repost" | "direct_message" | "followed";

export type ChannelAccessTokenKind = "invite" | "grant" | "share";

export type ProfileAssetView = { hash: string, mime: string, bytes: number, role: 'profile_avatar', };

export type AttachmentView = { hash: string, mime: string, bytes: number, role: string, status: BlobViewStatus, };

export type BlobMediaPayload = { bytes_base64: string, mime: string, };

export type ReplyPreviewAuthorView = { pubkey: string, name?: string | null, display_name?: string | null, picture?: string | null, picture_asset?: ProfileAssetView | null, };

export type ReplyPreviewView = { object_id: string, topic: string, author: ReplyPreviewAuthorView, content: string, attachments: Array<AttachmentView>, root_id?: string | null, reply_to?: string | null, };

export type ReactionKeyView = { reaction_key_kind: string, normalized_reaction_key: string, emoji?: string | null, custom_asset?: CustomReactionAssetView | null, };

export type ReactionSummaryView = { reaction_key_kind: string, normalized_reaction_key: string, emoji?: string | null, custom_asset?: CustomReactionAssetView | null, count: number, };

export type ReactionStateView = { target_object_id: string, source_replica_id: string, reaction_summary: Array<ReactionSummaryView>, my_reactions: Array<ReactionKeyView>, };

export type RecentReactionView = { reaction_key_kind: string, normalized_reaction_key: string, emoji?: string | null, custom_asset?: CustomReactionAssetView | null, updated_at: number, };

export type CustomReactionAssetView = { asset_id: string, owner_pubkey: string, blob_hash: string, search_key: string, mime: string, bytes: number, width: number, height: number, };

export type RepostSourceView = { source_object_id: string, source_topic_id: string, source_author_pubkey: string, source_author_name?: string | null, source_author_display_name?: string | null, source_author_picture?: string | null, source_author_picture_asset?: ProfileAssetView | null, source_object_kind: string, content: string, attachments: Array<AttachmentView>, reply_to?: string | null, root_id?: string | null, };

export type PostView = { object_id: string, envelope_id: string, author_pubkey: string, author_name?: string | null, author_display_name?: string | null, author_picture?: string | null, author_picture_asset?: ProfileAssetView | null, following: boolean, followed_by: boolean, mutual: boolean, friend_of_friend: boolean, content: string, content_status: BlobViewStatus, attachments: Array<AttachmentView>, created_at: number, reply_to?: string | null, reply_preview?: ReplyPreviewView | null, root_id?: string | null, object_kind: string, published_topic_id?: string | null, origin_topic_id?: string | null, repost_of?: RepostSourceView | null, repost_commentary?: string | null, is_threadable: boolean, channel_id?: string | null, audience_label: string, reaction_summary?: Array<ReactionSummaryView> | null, my_reactions?: Array<ReactionKeyView> | null, };

export type BookmarkedPostView = { bookmarked_at: number, post: PostView, };

export type AuthorSocialView = { author_pubkey: string, name?: string | null, display_name?: string | null, about?: string | null, picture?: string | null, picture_asset?: ProfileAssetView | null, updated_at?: number | null, following: boolean, followed_by: boolean, mutual: boolean, friend_of_friend: boolean, friend_of_friend_via_pubkeys: Array<string>, muted: boolean, };

export type DirectMessageStatusView = { peer_pubkey: string, dm_id: string, mutual: boolean, send_enabled: boolean, peer_count: number, pending_outbox_count: number, };

export type DirectMessageTopicStatusView = { topic: string, joined: boolean, peer_count: number, connected_peers: Array<string>, status_detail: string, last_error?: string | null, };

export type DirectMessageMessageView = { dm_id: string, message_id: string, sender_pubkey: string, recipient_pubkey: string, created_at: number, text: string, reply_to_message_id?: string | null, attachments: Array<AttachmentView>, outgoing: boolean, delivered: boolean, };

export type DirectMessageConversationView = { dm_id: string, peer_pubkey: string, peer_name?: string | null, peer_display_name?: string | null, peer_picture?: string | null, peer_picture_asset?: ProfileAssetView | null, updated_at: number, last_message_at?: number | null, last_message_id?: string | null, last_message_preview?: string | null, status: DirectMessageStatusView, };

export type NotificationView = { notification_id: string, kind: NotificationKind, actor_pubkey: string, actor_name?: string | null, actor_display_name?: string | null, actor_picture?: string | null, actor_picture_asset?: ProfileAssetView | null, source_envelope_id?: string | null, source_replica_id?: string | null, topic_id?: string | null, channel_id?: string | null, object_id?: string | null, thread_root_object_id?: string | null, dm_id?: string | null, message_id?: string | null, preview_text?: string | null, created_at: number, received_at: number, read_at?: number | null, };

export type NotificationStatusView = { unread_count: number, };

export type TimelineView = { items: Array<PostView>, next_cursor?: TimelineCursor | null, };

export type DirectMessageTimelineView = { items: Array<DirectMessageMessageView>, next_cursor?: TimelineCursor | null, };

export type JoinedPrivateChannelView = { topic_id: string, channel_id: string, label: string, creator_pubkey: string, owner_pubkey: string, joined_via_pubkey?: string | null, audience_kind: ChannelAudienceKind, is_owner: boolean, current_epoch_id: string, archived_epoch_ids: Array<string>, sharing_state: ChannelSharingState, rotation_required: boolean, participant_count: number, stale_participant_count: number, };

export type PrivateChannelEpochCapability = { epoch_id: string, namespace_secret_hex: string, };

export type PrivateChannelCapability = { topic_id: string, channel_id: string, label: string, creator_pubkey: string, owner_pubkey: string, joined_via_pubkey?: string | null, audience_kind: ChannelAudienceKind, current_epoch_id: string, current_epoch_secret_hex: string, archived_epochs: Array<PrivateChannelEpochCapability>, rotation_required: boolean, participant_count: number, stale_participant_count: number, namespace_secret_hex: string, };

export type ChannelAccessTokenExport = { kind: ChannelAccessTokenKind, token: string, };

export type ChannelAccessTokenPreview = { kind: ChannelAccessTokenKind, topic_id: string, channel_id: string, channel_label: string, owner_pubkey: string, inviter_pubkey?: string | null, sponsor_pubkey?: string | null, epoch_id: string, };

export type TopicSyncStatus = { topic: string, joined: boolean, delivery_state: DeliveryState, peer_count: number, connected_peers: Array<string>, docs_assist_peer_ids: Array<string>, configured_peer_ids: Array<string>, missing_peer_ids: Array<string>, active_path: ConnectionPath, rendezvous_peer_ids: Array<string>, fallback_peer_ids: Array<string>, last_received_at?: number | null, last_docs_activity_at?: number | null, status_detail: string, last_error?: string | null, };

export type DiscoveryStatus = { mode: DiscoveryMode, connect_mode: ConnectMode, active_path: ConnectionPath, fallback_peer_ids: Array<string>, env_locked: boolean, configured_seed_peer_ids: Array<string>, bootstrap_seed_peer_ids: Array<string>, manual_ticket_peer_ids: Array<string>, connected_peer_ids: Array<string>, docs_assist_peer_ids: Array<string>, blob_assist_peer_ids: Array<string>, local_endpoint_id: string, last_discovery_error?: string | null, };

export type SyncStatus = { connected: boolean, delivery_state: DeliveryState, last_sync_ts?: number | null, peer_count: number, pending_events: number, status_detail: string, last_error?: string | null, configured_peers: Array<string>, subscribed_topics: Array<string>, active_path: ConnectionPath, fallback_peer_ids: Array<string>, topic_diagnostics: Array<TopicSyncStatus>, local_author_pubkey: string, discovery: DiscoveryStatus, gossip_disabled_topics: Array<string>, gossip_disabled_channels: Array<string>, };

export type LiveSessionStatus = "Scheduled" | "Live" | "Paused" | "Ended";

export type LiveSessionView = { session_id: string, host_pubkey: string, title: string, description: string, status: LiveSessionStatus, started_at: number, ended_at?: number | null, viewer_count: number, joined_by_me: boolean, channel_id?: string | null, audience_label: string, };

export type GameRoomStatus = "Waiting" | "Running" | "Paused" | "Ended";

export type GameRoomKind = "score_game" | "metaverse_room";

export type GameScoreView = { participant_id: string, label: string, score: number, };

export type MetaverseAssetKind = "vrm" | "glb" | "texture" | "other";

export type MetaverseAssetRef = { kind: MetaverseAssetKind, blob_hash: string, mime_type?: string | null, size_bytes?: number | null, name?: string | null, };

export type MetaversePrimitive = "cube" | "sphere";

export type MetaverseRoomPresenceV1 = { room_id: string, peer_id: string, display_name?: string | null, avatar_asset_ref?: MetaverseAssetRef | null, joined_at: number, last_seen_at: number, };

export type MetaverseAvatarTransformV1 = { room_id: string, peer_id: string, seq: number, position: [number, number, number], rotation: [number, number, number], animation?: string | null, sent_at: number, };

export type MetaverseRoomChatMessageV1 = { room_id: string, message_id: string, author_peer_id: string, display_name?: string | null, body: string, created_at: number, };

export type SharedRoomObjectV1 = { object_id: string, asset_ref?: MetaverseAssetRef | null, primitive_fallback: MetaversePrimitive, position: [number, number, number], rotation: [number, number, number], scale: [number, number, number], updated_by: string, updated_at: number, };

export type MetaverseRoomEventV1 = { "type": "presence_join", presence: MetaverseRoomPresenceV1, } | { "type": "presence_leave", room_id: string, peer_id: string, left_at: number, } | { "type": "avatar_transform", transform: MetaverseAvatarTransformV1, } | { "type": "chat_message", message: MetaverseRoomChatMessageV1, } | { "type": "object_update", object: SharedRoomObjectV1, };

export type MetaverseRoomEventEnvelopeContentV1 = { event_id: string, topic_id: string, channel_id?: string | null, room_id: string, peer_id: string, seq: number, sent_at: number, event: MetaverseRoomEventV1, };

export type MetaverseRoomSceneV1 = { ground: string, shared_object: SharedRoomObjectV1, };

export type MetaverseRoomSpawnV1 = { position: [number, number, number], rotation: [number, number, number], };

export type MetaverseRoomStateV1 = { world_version: number, max_peers?: number | null, scene: MetaverseRoomSceneV1, default_spawn: MetaverseRoomSpawnV1, asset_refs: Array<MetaverseAssetRef>, chat_history?: Array<MetaverseRoomChatMessageV1> | null, };

export type GameRoomView = { room_id: string, host_pubkey: string, title: string, description: string, status: GameRoomStatus, phase_label?: string | null, scores: Array<GameScoreView>, room_kind: GameRoomKind, metaverse?: MetaverseRoomStateV1 | null, manifest_blob_hash: string, updated_at: number, channel_id?: string | null, audience_label: string, };

export type MetaverseRoomEventView = { envelope_id: string, content: MetaverseRoomEventEnvelopeContentV1, envelope: Record<string, unknown>, received_at: number, source_peer: string, };

export type Pubkey = string;

export type TopicId = string;

export type ChannelId = string;

export type ChannelRef = { "kind": "public" } | { "kind": "private_channel", channel_id: ChannelId, };

export type TimelineScope = { "kind": "public" } | { "kind": "all_joined" } | { "kind": "channel", channel_id: ChannelId, };

export type SeedPeer = { endpoint_id: string, addr_hint?: string | null, };

export type Profile = { pubkey: Pubkey, name?: string | null, display_name?: string | null, about?: string | null, picture?: string | null, picture_asset?: ProfileAssetView | null, updated_at: number, };

export type PrivateChannelInvitePreview = { channel_id: ChannelId, topic_id: TopicId, channel_label: string, inviter_pubkey: Pubkey, owner_pubkey: Pubkey, epoch_id: string, expires_at?: number | null, namespace_secret_hex: string, };

export type FriendOnlyGrantPreview = { channel_id: ChannelId, topic_id: TopicId, channel_label: string, owner_pubkey: Pubkey, epoch_id: string, expires_at?: number | null, namespace_secret_hex: string, };

export type FriendPlusSharePreview = { channel_id: ChannelId, topic_id: TopicId, channel_label: string, owner_pubkey: Pubkey, sponsor_pubkey: Pubkey, epoch_id: string, expires_at?: number | null, namespace_secret_hex: string, share_token_id: string, };

export type DiscoveryConfig = { mode: DiscoveryMode, connect_mode: ConnectMode, env_locked: boolean, seed_peers: Array<SeedPeer>, };

export type CommunityNodeSeedPeer = { endpoint_id: string, addr_hint?: string | null, };

export type CommunityNodeResolvedUrls = { public_base_url: string, connectivity_urls: Array<string>, seed_peers?: Array<CommunityNodeSeedPeer> | null, };

export type CommunityNodeNodeConfig = { base_url: string, auto_approve?: boolean | null, resolved_urls?: CommunityNodeResolvedUrls | null, };

export type CommunityNodeConfig = { nodes: Array<CommunityNodeNodeConfig>, };

export type CommunityNodeAuthState = { authenticated: boolean, expires_at?: number | null, };

export type CommunityNodeConsentItem = { policy_slug: string, policy_version: number, title: string, body?: string | null, required: boolean, accepted_at?: number | null, 
/**
 * その policy_slug で過去に同意した最大 version（version 不問）。
 * `accepted_at` が None でこれが Some なら、版が上がって再同意が必要な「更新」を意味する。
 */
previously_accepted_version?: number | null, };

export type CommunityNodeConsentStatus = { all_required_accepted: boolean, items: Array<CommunityNodeConsentItem>, };

export type CommunityNodeSessionPhase = "idle" | "connecting" | "authenticating" | "accepting" | "refreshing" | "ready" | "retrying";

export type CommunityNodeNodeStatus = { base_url: string, auto_approve?: boolean | null, auth_state: CommunityNodeAuthState, consent_state?: CommunityNodeConsentStatus | null, resolved_urls?: CommunityNodeResolvedUrls | null, last_error?: string | null, session_phase?: CommunityNodeSessionPhase | null, retry_after?: number | null, restart_required: boolean, };

export type CommunityNodeCapabilityScope = { available_enabled: Array<string>, planned_enabled: Array<string>, };

export type CommunityNodeAuthorityScope = { applies_to: Array<string>, does_not_apply_to: Array<string>, };

export type CommunityNodeP2pBoundary = { identity_authority: boolean, profile_canonical_store: boolean, social_graph_canonical_store: boolean, content_truth_source: boolean, network_wide_authority: boolean, };

export type CommunityNodeManifest = { node_id: string, node_name: string, node_role: string, server_name: string, manifest_version: string, capability_scope: CommunityNodeCapabilityScope, authority_scope: CommunityNodeAuthorityScope, p2p_boundary: CommunityNodeP2pBoundary, abuse_contact: string, 
/**
 * node が公開する通報受付 endpoint(#310)。未公開の場合は空文字。
 * client は空なら `abuse_contact` を mailto / copyable contact として案内する。
 */
report_endpoint: string, terms_url: string, privacy_url: string, moderation_policy_url: string, };

export type CommunityNodeManifestFetchStatus = "ok" | "absent";

export type CommunityNodeManifestFetch = { status: CommunityNodeManifestFetchStatus, manifest?: CommunityNodeManifest | null, };

export type CommunityNodeIndexQueryRequest = { base_url: string, query?: string | null, scope_kind?: IndexScopeKind | null, scope_id?: string | null, limit?: number | null, };

export type CommunityNodeIndexQueryError = { code: string, message: string, status?: number | null, retry_after_seconds?: number | null, };

export type CommunityNodeIndexingRequest = { base_url: string, scope_kind: IndexScopeKind, 
/**
 * public の target、private capability の親 topic。
 */
topic_id: string, 
/**
 * private の target。public では指定しない。
 */
channel_id?: string | null, 
/**
 * private secret の外部送信を UI で明示確認したことを示す。
 */
confirm_private_channel_secret_disclosure: boolean, };

export type CommunityNodeIndexingRequestError = { code: string, message: string, status?: number | null, retry_after_seconds?: number | null, };

export type IndexScopeKind = "public_topic" | "private_channel";

export type IndexingRequestStatus = "pending" | "approved" | "rejected";

export type IndexEntryView = { scope_kind: IndexScopeKind, scope_id: string, object_id: string, author_pubkey: string, text: string, created_at: number, };

export type IndexQueryResponse = { entries: Array<IndexEntryView>, };

export type SubmitIndexingRequestResponse = { request_id: string, status: IndexingRequestStatus, };

export type SubmitCommunityNodeReportRequest = { 
/**
 * 通報先 node の base url（記録・表示用）。
 */
node_base_url: string, 
/**
 * node manifest が公開する通報受付 endpoint（絶対 http(s) URL）。
 */
report_endpoint: string, 
/**
 * 通報対象の種別（post / profile / media / search_result / recommendation 等）。
 */
subject_kind: string, 
/**
 * 通報対象の識別子（post id / pubkey / object id 等）。
 */
subject_id: string, 
/**
 * 通報先となった node capability（community_index / moderation / media_cache 等）。
 */
capability: string, 
/**
 * 通報理由カテゴリ。
 */
reason: string, 
/**
 * 任意の補足説明。
 */
details?: string | null, 
/**
 * 任意の通報者連絡先（node が follow-up に使える）。
 */
reporter_contact?: string | null, };

export type SubmitCommunityNodeReportStatus = "submitted";

export type SubmitCommunityNodeReportResult = { status: SubmitCommunityNodeReportStatus, 
/**
 * node が返した受付参照 ID（任意）。
 */
reference_id?: string | null, };

export type RuntimeEvent = { "type": "notification_status_changed" } | { "type": "sync_status_changed", sync_status?: SyncStatus | null, community_node_statuses?: Array<CommunityNodeNodeStatus> | null, };

export type CreatePostRequest = { topic: string, content: string, reply_to?: string | null, channel_ref: ChannelRef, attachments: Array<CreateAttachmentRequest>, };

export type CreateRepostRequest = { topic: string, source_topic: string, source_object_id: string, commentary?: string | null, };

export type CreateAttachmentRequest = { file_name?: string | null, mime: string, byte_size: number, data_base64: string, role?: string | null, };

export type ReactionKeyRequest = { "kind": "emoji", emoji: string, } | { "kind": "custom_asset", asset_id: string, owner_pubkey: string, blob_hash: string, search_key: string, mime: string, bytes: number, width: number, height: number, };

export type ToggleReactionRequest = { target_topic_id: string, target_object_id: string, reaction_key: ReactionKeyRequest, channel_ref?: ChannelRef | null, };

export type CustomReactionCropRect = { x: number, y: number, size: number, };

export type CreateCustomReactionAssetRequest = { upload: CreateAttachmentRequest, crop_rect: CustomReactionCropRect, search_key: string, };

export type BookmarkCustomReactionRequest = { asset_id: string, owner_pubkey: string, blob_hash: string, search_key: string, mime: string, bytes: number, width: number, height: number, };

export type RemoveBookmarkedCustomReactionRequest = { asset_id: string, };

export type BookmarkPostRequest = { topic: string, object_id: string, };

export type RemoveBookmarkedPostRequest = { object_id: string, };

export type ListRecentReactionsRequest = { limit?: number | null, };

export type ListTimelineRequest = { topic: string, scope: TimelineScope, cursor?: TimelineCursor | null, limit?: number | null, };

export type ListThreadRequest = { topic: string, thread_id: string, cursor?: TimelineCursor | null, limit?: number | null, };

export type ListProfileTimelineRequest = { pubkey: string, cursor?: TimelineCursor | null, limit?: number | null, };

export type ImportPeerTicketRequest = { ticket: string, };

export type UnsubscribeTopicRequest = { topic: string, };

export type SetTopicGossipEnabledRequest = { topic: string, enabled: boolean, };

export type SetChannelGossipEnabledRequest = { topic: string, channel: string, enabled: boolean, };

export type GetBlobPreviewRequest = { hash: string, mime: string, };

export type GetBlobMediaRequest = { hash: string, mime: string, };

export type AuthorRequest = { pubkey: string, };

export type ListSocialConnectionsRequest = { kind: SocialConnectionKind, };

export type DirectMessageRequest = { pubkey: string, };

export type NotificationIdRequest = { notification_id: string, };

export type ListDirectMessageMessagesRequest = { pubkey: string, cursor?: TimelineCursor | null, limit?: number | null, };

export type SendDirectMessageRequest = { pubkey: string, text?: string | null, reply_to_message_id?: string | null, attachments: Array<CreateAttachmentRequest>, };

export type DeleteDirectMessageMessageRequest = { pubkey: string, message_id: string, };

export type SetMyProfileRequest = { name?: string | null, display_name?: string | null, about?: string | null, picture?: string | null, picture_upload?: CreateAttachmentRequest | null, clear_picture: boolean, };

export type ListLiveSessionsRequest = { topic: string, scope: TimelineScope, };

export type CreateLiveSessionRequest = { topic: string, channel_ref: ChannelRef, title: string, description: string, };

export type LiveSessionCommandRequest = { topic: string, session_id: string, };

export type ListGameRoomsRequest = { topic: string, scope: TimelineScope, };

export type CreateGameRoomRequest = { topic: string, channel_ref: ChannelRef, title: string, description: string, participants: Array<string>, };

export type CreateMetaverseRoomRequest = { topic: string, channel_ref: ChannelRef, title: string, description: string, max_peers?: number | null, };

export type PublishMetaverseRoomEventRequest = { topic: string, room_id: string, peer_id: string, seq: number, event: MetaverseRoomEventV1, };

export type ListMetaverseRoomEventsRequest = { topic: string, room_id: string, after_envelope_id?: string | null, limit?: number | null, };

export type ImportMetaverseRoomAssetRequest = { topic: string, room_id: string, kind: MetaverseAssetKind, mime_type: string, name?: string | null, data_base64: string, };

export type CreatePrivateChannelRequest = { topic: string, label: string, audience_kind: ChannelAudienceKind, };

export type ExportPrivateChannelInviteRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportPrivateChannelInviteRequest = { token: string, };

export type ExportChannelAccessTokenRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportChannelAccessTokenRequest = { token: string, };

export type PreviewChannelAccessTokenRequest = { token: string, };

export type ExportFriendOnlyGrantRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportFriendOnlyGrantRequest = { token: string, };

export type ExportFriendPlusShareRequest = { topic: string, channel_id: string, expires_at?: number | null, };

export type ImportFriendPlusShareRequest = { token: string, };

export type FreezePrivateChannelRequest = { topic: string, channel_id: string, };

export type RotatePrivateChannelRequest = { topic: string, channel_id: string, };

export type LeavePrivateChannelRequest = { topic: string, channel_id: string, };

export type ListJoinedPrivateChannelsRequest = { topic: string, };

export type UpdateGameRoomRequest = { topic: string, room_id: string, status: GameRoomStatus, phase_label?: string | null, scores: Array<GameScoreView>, };

export type UpdateMetaverseRoomRequest = { topic: string, room_id: string, status: GameRoomStatus, shared_object_position: [number, number, number], shared_object_rotation: [number, number, number], shared_object_scale: [number, number, number], };

export type SetCommunityNodeConfigNode = { base_url: string, auto_approve: boolean, };

export type SetCommunityNodeConfigRequest = { nodes: Array<SetCommunityNodeConfigNode>, };

export type CommunityNodeTargetRequest = { base_url: string, };

export type AcceptCommunityNodeConsentsRequest = { base_url: string, policy_slugs: Array<string>, };

export type SetDiscoverySeedsRequest = { seed_entries: Array<string>, };

